server:
  port: 13000
  forward-headers-strategy: framework

spring:
  config:
    activate:
      on-profile: "local"

  cloud:
    gateway:
      # cores 처리
      # 각 서비스 모듈은 웹브라우저와 직접 통신하지 않으므로 단일진입점인 gateway 담당
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL_BASE:http://localhost:5173}
            allowedMethods:
              - OPTIONS
              - HEAD
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - 'Content-Type'
              - 'Authorization'
            allowCredentials: true

      # eureka server 에 등록된 client 찾아서 사용자의 url_pattern을 매핑하는 작업
      routes:
        - id: auth-service
          predicates:
            - Path=/app/auth/**, /app/oauth2/**
          filters:
            - StripPrefix=1
          uri: http://localhost:12321

        - id: user-service
          predicates:
            - Path=/app/users/**
          filters:
            # 첫번째 접두어를 제거하라는 의미
            # browser : http://server.xxxxx.shop/user-service/users/signIn
            # inner   : http://server.xxxxx.shop/users/signIn
            - StripPrefix=1
          uri: http://localhost:12322

        - id: schedule-service
          predicates:
            - Path=/app/schedules/**
          filters:
            # 첫번째 접두어를 제거하라는 의미
            # browser : http://server.xxxxx.shop/product-service/product/create
            # inner   : http://server.xxxxx.shop/product/signIn
            - StripPrefix=1
          uri: http://localhost:12323