server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    default: local

  cloud:
    gateway:
      # cores 처리
      # 각 서비스 모듈은 웹브라우저와 직접 통신하지 않으므로 단일진입점인 gateway 담당
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL_BASE:http://localhost:5173}
            allowedMethods:
              - OPTIONS
              - HEAD
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - 'Content-Type'
              - 'Authorization'
            allowCredentials: true

      # eureka server 에 등록된 client 찾아서 사용자의 url_pattern을 매핑하는 작업
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: http://user-service

        - id: certificate-service
          predicates:
            - Path=/certificate-service/**
          filters:
            - StripPrefix=1
          uri: http://certificate-service

        - id: auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
          uri: http://auth-service

        - id: schedule-service
          predicates:
            - Path=/schedule-service/**
          filters:
            - StripPrefix=1
          uri: http://schedule-service

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:inspire-mini-project-team-4-access-secret-key}
    expires: ${JWT_ACCESS_EXPIRES:1800000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:inspire-mini-project-team-4-refresh-secret-key}
    expires: ${JWT_REFRESH_EXPIRES:1209600000}