apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: lgcns

spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/auth:latest  # ECR 경로

          ports:
          - containerPort: 8080
          
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            
            # --- User 서비스 연결 (중요!) ---
            - name: USER_URL_BASE
              value: "http://user-service:80"
              
            - name: APP_USER_URL # 👈 이 줄을 추가하세요!
              value: "user-service:80"

           
            
            # --- Redis (필요시 수정) ---
            - name: REDIS_HOST
              value: "redis-service" # Redis 서비스 이름에 맞게 수정하세요
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_HOST
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_ADMIN
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_PASSWORD

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://$(DATABASE_HOST):3306/auth?useSSL=true&verifyServerCertificate=false"
            
            # --- 추가 확인 ---
            - name: SPRING_DATASOURCE_USERNAME # 스프링 부트 표준 변수명도 같이 넣어주면 더 안전합니다.
              value: "$(DATABASE_USERNAME)"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "$(DATABASE_PASSWORD)"

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: lgcns
spec:
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 8080