server:
  port: 8080

spring:
  application:
    name: auth-service

  profiles:
    default: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: ${GOOGLE_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            client-name: ${KAKAO_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: ${NAVER_CLIENT_NAME}
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: ${GOOGLE_USER_NAME_ATTRIBUTE_NAME}
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE_NAME}
          naver:
            authorization-uri: ${NAVER_AUTHORIZATION_URI}
            token-uri: ${NAVER_TOKEN_URI}
            user-info-uri: ${NAVER_USER_INFO_URI}
            user-name-attribute: ${NAVER_USER_NAME_ATTRIBUTE_NAME}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always


jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:inspire-mini-project-team-4-access-secret-key}
    expires: ${JWT_ACCESS_EXPIRES:1800000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:inspire-mini-project-team-4-refresh-secret-key}
    expires: ${JWT_REFRESH_EXPIRES:1209600000}

app:
  frontend:
    url:
      base: ${FRONTEND_URL_BASE:http://localhost:5173}
      registration: ${FRONTEND_URL_REGISTRATION:http://localhost:5173/oauth-register}
      login-success: ${FRONTEND_URL_LOGIN_SUCCESS:http://localhost:5173/login-success}
      login-failure: ${FRONTEND_URL_LOGIN_FAILURE:http://localhost:5173/login-failure}