server:
  port: 8080

spring:
  application:
    name: schedule-service

  profiles:
    default: local
    
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/schedule?useSsl=false # DB 이름 확인 필수
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always