server:
  port: 8080

spring:
  application:
    name: user-service

  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always