# eks 배포 시 apigateway는 eureka server에 등록하지 않겠다, 라는 의미
eureka:
  client:
    enabled: false

spring:
  application:
    name: certificate-service # 이름

  # 환경변수가 들어오면 그걸 쓰고, 없으면 local을 쓰도록 변경
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # mariadb settings
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # localhost 대신 환경변수 처리. (로컬 실행 시엔 localhost 적용됨)
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/inspire?useSSL=true&verifyServerCertificate=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456789}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate: 
      ddl-auto: update  # create로 변경 주의
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 쿼리를 보기 좋게 줄바꿈하여 출력

  kafka:
    # 카프카 주소도 환경변수 처리 (나중에 EKS에 올릴 때 kafka-service로 주입)
    kafka-server: ${KAFKA_HOST:localhost}:9092

# # Feign + CircuitBreaker 트랜젝션 처리
feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 10s

api:
  qnet:
    # 보안상 API 키도 환경변수로 빼두는 것이 정석
    service-key: ${QNET_SERVICE_KEY:080898119fe0e5ab80852b1bca728dbbbf71d52f1299f581a1c8730fe076b7fc}
    certificate-url: http://openapi.q-net.or.kr/api/service/rest/InquiryListNationalQualifcationSVC/getList
    schedule-url: http://apis.data.go.kr/B490007/qualExamSchd/getQualExamSchdList
