plugins {
	id 'spring-web-conventions'
}

version = '1.0.0'

dependencies {
	// 공공API XML 파싱
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'

	// WebClient (공공API 호출용)
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

	// XML 처리를 위한 Jackson 데이터포맷 라이브러리
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
}