apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-deployment
  namespace: lgcns

spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: schedule

  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: schedule
          image: 613307913976.dkr.ecr.ap-northeast-2.amazonaws.com/schedule:latest   # ECR 경로

          ports:
          - containerPort: 8080
          
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_ADMIN
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-db-secret
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://$(DB_HOST):3306/schedule?useSSL=true&verifyServerCertificate=false"

---

apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  namespace: lgcns
spec:
  selector:
    app: schedule
  ports:
    - port: 80
      targetPort: 8080